# Generated by Django 3.2.18 on 2023-06-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='Service',
            new_name='service',
        ),
    ]
